task-JDP201202-4
danieloginski/project-jdp-2012-02 pull request #11
Opened 2020-12-17 18:46 UTC by severinum

OrderController - wstępna implementacja endpontów

2020-12-17 20:12 UTC, danieloginski commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:8889/kodilla_project?serverTimezone=Europe/London&useSSL=False
tę zmianę trzeba wycofać

2020-12-17 20:13 UTC, danieloginski commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +     * **/
takie rzeczy raczej na czacie / spotkaniu, taki java doc nam niewiele wnosi

2020-12-17 20:14 UTC, danieloginski requested changes
za dużo zmian jest w tym PR, do zrobienia był tylko kontroler z fake danymi + ewentualnie dto

2020-12-17 20:46 UTC, severinum commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +     * **/
Nie ma tego już tylko nie wiedziałem jak zrobić nowy commit

2020-12-17 21:11 UTC, severinum commented
wymaga zmian ...

2020-12-18 15:01 UTC, danieloginski commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:8889/kodilla_project?serverTimezone=Europe/Warsaw&useSSL=False
Z czego wynika ta zmiana portu? czy zostało to ustalone z zespołem?

2020-12-18 15:03 UTC, danieloginski requested changes
@severinum

2020-12-18 15:27 UTC, closed without merging