task-JDP201202-24
danieloginski/project-jdp-2012-02 pull request #22
Opened 2020-12-19 22:28 UTC by severinum

task-JDP201202-24 OrderController-rzeczywista implementacja metod

2020-12-20 20:14 UTC, danieloginski commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    public OrderController(OrderMapper orderMapper, OrderDbService orderDbService) {
`@RequiredArgsConstructor`

2020-12-20 20:16 UTC, danieloginski commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +        order.setDateTime(LocalDateTime.now());
czy `LocalDateTime.now() `nie mogłoby być domyślną wartością `dateTime` w `Order`?

2020-12-20 20:17 UTC, danieloginski commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    public void setDateTime(LocalDateTime now) {
pusta metoda

2020-12-20 20:18 UTC, danieloginski commented on src/main/java/com/kodilla/ecommercee/service/OrderDbService.java
> +    public OrderDbService(OrderRepository orderRepository) {
`@RequiredArgsConstructor`

2020-12-20 20:19 UTC, danieloginski requested changes
@severinum

2020-12-21 08:18 UTC, severinum commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +        order.setDateTime(LocalDateTime.now());
miałem ale przekazywało nulla więc wstawiłem , zmienia ...

2020-12-21 16:26 UTC, danieloginski commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +
dużo pustych linii - do posprzątania

2020-12-21 16:26 UTC, danieloginski approved these changes

2020-12-21 16:53 UTC, merged