Task jdp201202-18
danieloginski/project-jdp-2012-02 pull request #28
Opened 2021-01-02 14:37 UTC by wezik

Implementacja testów CRUD dla encji Group

2021-01-02 18:06 UTC, AdamTomys approved these changes

2021-01-02 22:31 UTC, danieloginski commented on src/test/java/com/kodilla/ecommercee/service/GroupDbServiceTest.java
> +    public void group_CRUD() {
nadaj testowi bardziej znaczącą nazwę

2021-01-02 22:31 UTC, danieloginski commented on src/test/java/com/kodilla/ecommercee/service/GroupDbServiceTest.java
> +        //Create
do usunięcia

2021-01-02 22:31 UTC, danieloginski commented on src/test/java/com/kodilla/ecommercee/service/GroupDbServiceTest.java
> +            //Given
do usunięcia

2021-01-02 22:32 UTC, danieloginski commented on src/test/java/com/kodilla/ecommercee/service/GroupDbServiceTest.java
> +        //Update
do usunięcia

2021-01-02 22:33 UTC, danieloginski commented on src/test/java/com/kodilla/ecommercee/service/GroupDbServiceTest.java
> +public class GroupDbServiceTest {
napisz pojedyncze testy pod każdą metodę, zamiast wszystko w jednym

2021-01-02 22:34 UTC, danieloginski requested changes
@wezik

2021-01-05 11:08 UTC, danieloginski approved these changes

2021-01-05 13:00 UTC, merged