Task-JDP201202-17
danieloginski/project-jdp-2012-02 pull request #31
Opened 2021-01-06 17:42 UTC by AdamTomys

Nie działa u mnie usuwanie grupy z DB metodą GroupDbService od Dominika - do sprawdzenia @wezik

2021-01-07 12:58 UTC, AdamTomys commented
Zrezygnowałem z początkowo zastosowanych dbService w testach encji na rzecz bezpośredniego użycia repo.
Uznałem, że testy serwisów powinny być ujęte w testach Controller.

2021-01-07 13:15 UTC, danieloginski commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        try {
ten `try-catch` tutaj potrzebny?

2021-01-07 13:18 UTC, danieloginski commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +    public void testDbRelationsBeforeAndAfterDeleteProduct() {
Trochę dużo się tu dzieje, spróbuj w miarę możliwości powynosić setup testów (sekcja given) do metod, w when też dzieje się sporo, normalnie powinno się tam znaleźć wywołanie jednej metody, którą testujesz.

2021-01-07 13:19 UTC, danieloginski requested changes
@AdamTomys

2021-01-07 18:15 UTC, AdamTomys commented
Zrobiłem optymalizację, podzieliłem ostatni test na dwa osobne, pozbyłem się kilku zmiennych, mam nadzieję, że będzie ok.
Sprawdzone bezpośrednio w DB, wszystko dobrze się czyści, łącznie z zależnościami.

2021-01-09 13:56 UTC, wezik approved these changes

2021-01-10 17:04 UTC, danieloginski approved these changes

2021-01-11 09:57 UTC, merged